using System.Diagnostics;
using xlang.Compiler.SemanticAnalysis;
using xlang.Compiler.Structures;
using xlang.Compiler.Structures.AST;
using xlang.Compiler.Utils;

namespace xlang.Compiler.CodeGeneration;

public enum ValKind
{
    Imm, Mem, Gpr, Xmm
}

public enum OptimizationLevel
{
    None,
    Regular
}

public class CodeGenerator
{
    private AssemblyWriter _writer = new();

    private OptimizationLevel _optimizationLevel = OptimizationLevel.None;

    private bool _isMain = false;
    private int _rspParity = 0;
    private string _currentBreakLabel;
    private int _localsSize;
    private int _tempCursor = 0;
    private int _tempMax = 0;


    private Module _module;
    private ProgramDeclaration _program;
    private SemanticModel _model;
    private string _source;

    private FunctionDeclaration _currentFunction;
    private FunctionMetaData _currentFunctionMetaData;

    private bool[] _parameterSpilled = [false, false, false, false];
    private readonly List<TempHandle> _currentParameters = [];


    //private RegPool _regs;// = new();
    private TemporaryPool _regPool;

    public CodeGenerator(Module module, SemanticModel semanticModel, string source)
    {
        _module = module;
        _program = module.Program;
        _model = semanticModel;
        _source = source;

        _regPool = new TemporaryPool((op0, op1) => Move(op0, op1), (op0, op1) => Exchange(op0, op1));
    }

    public string Generate()
    {
        Logger.LogDebug($"Generating machine code {_program.Id}");

        List<string> externalFunction = ["ExitProcess", "GetProcessHeap", "HeapAlloc",
            ..(!_model.ExternalFunctions.ContainsKey(_module.Id) ?[]: _model.ExternalFunctions[_module.Id]
                .Select(y => Utils.Utils.SanitizeFqn(_model.GetSymbol<CallableSymbol>(y).FullyQualifiedName)))];
        var globals = _model.Symbols.Values.Where(x => x is FunctionSymbol { AccessType: EAccessType.Public } fs && x.OwnerModule.Program.Id == _program.Id).Select(y => Utils.Utils.SanitizeFqn((y as FunctionSymbol).FullyQualifiedName)).ToList();


        if (_model.GetEntryPoint()?.OwnerModule.Program.Id == _program.Id)
        {
            var label = Utils.Utils.SanitizeFqn(_model.GetEntryPoint()!.FullyQualifiedName);

            if (!globals.Contains(label))
            {
                globals.Add(label);
            }
        }

        GenerateSignature();

        _writer.Append("bits 64", false);
        _writer.Append("default rel", false);

        _writer.Append("section .rdata", false);

        for (var i = 0; i < _model.LiteralConstants.Count; i++)
        {
            _writer.Append(_model.LiteralConstants[i] switch
            {
                StringConstant s => $"LC{i}:\tdb \"{s.Text}\"".PadRight(50) + $"; {s.Text}",
                FloatConstant f => $"LC{i}:\tdd 0x{BitConverter.SingleToInt32Bits(f.Value):X8}".PadRight(50) + $"; {f.Value}f",
                _ => throw new ArgumentOutOfRangeException()
            }, false);
        }

        _writer.Append("section .text", false);
        if (externalFunction.Count != 0)
            _writer.Append($"extern {string.Join(", ", externalFunction)}");
        if (globals.Count != 0)
            _writer.Append($"global {string.Join(", ", globals)}");
        _writer.Append("");

        GenerateScope(_program.Body);

        return _writer.ToString();
    }

    public void GenerateSignature()
    {
        string[] lines = [
            "Generated by XLC version 0.0.0.1",
            $"{DateTime.Now:yyyy-MM-dd HH:mm}",
            $"Optimization: {_optimizationLevel}"
        ];

        var maxLength = lines.Max(x => x.Length);

        _writer.Comment($"##{"".PadRight(maxLength,'#')}##");
        foreach (var line in lines)
        {
            _writer.Comment($"# {line.PadRight(maxLength)} #");
        }
        _writer.Comment($"##{"".PadRight(maxLength, '#')}##");
    }

    public void GenerateScope(ScopeBody scope)
    {
        foreach (var s in scope.Scopes)
        {
            GenerateScope(s.Body);
        }
        foreach (var c in scope.Classes)
        {
            GenerateClass(c);
        }

        foreach (var f in scope.Functions)
        {
            if (f.IsExtern)
                continue;

            _currentFunction = f;
            GenerateFunction(f);
        }

    }

    public void GenerateClass(ClassDeclaration classDeclaration)
    {
        foreach (var member in classDeclaration.Members)
        {
            if (member is FunctionDeclaration methodDeclaration)
            {
                GenerateFunction(methodDeclaration);
            }
        }
    }

    public void GenerateFunction(FunctionDeclaration function)
    {
        var functionSymbol = _model.GetSymbol<FunctionSymbol>(function.Id);
        var meta = _model.FunctionData[functionSymbol.Id];
        _currentFunctionMetaData = meta;
        _isMain = _model.EntryPoint == functionSymbol.Id;
        _rspParity = 0;
        _tempCursor = 0;
        _tempMax = 0;
        _localsSize = meta.LocalsSize;
        _currentFunction = function;
        _writer.Label(Utils.Utils.SanitizeFqn(functionSymbol.FullyQualifiedName));


        for (var i = 0; i < _parameterSpilled.Length; i++)
            _parameterSpilled[i] = false;


        _regPool.Reset();

        foreach (var parSymId in functionSymbol.Parameters)
        {
            var parSym = _model.GetSymbol<ParameterSymbol>(parSymId);
            var tmp = _regPool.AcquireParameter(parSym.Index, parSym.Type.IsFloat);

            _currentParameters.Add(tmp);
        }


        //EmitFunctionPrologue(function);
        _writer.Append("___prologue___", false);
        EmitStatement(function.Body!);



        if (functionSymbol.Type == Types.Void)
        {
            if (_isMain)
            {
                Move(RegisterOperand.Rcx, ImmediateOperand.Zero);
                EmitFunctionCall("ExitProcess", 0);
            }
            else
            {
                if (!_currentFunctionMetaData.IsLeaf)
                {
                    Move(RegisterOperand.Rsp, RegisterOperand.Rbp);
                    Pop(RegisterOperand.Rbp);
                }
                _writer.Append("ret");
            }
        }
        InsertFunctionPrologue(function);
    }

    public void InsertFunctionPrologue(FunctionDeclaration function)
    {
        var functionSymbol = _model.GetSymbol<FunctionSymbol>(function.Id);
        //var meta = _model.FunctionData[functionSymbol.Id];

        _writer.SetReplaceLine("___prologue___");

        _writer.Comment($"Locals: {_currentFunctionMetaData.LocalsSize} bytes");
        _writer.Comment($"Leaf: {_currentFunctionMetaData.IsLeaf}");
        _writer.Comment($"Params: \n{string.Join('\n', functionSymbol.Parameters.Select((x, i) =>
            $"{_model.GetSymbol(x).Name}: {AssemblyUtils.GetParameterRegister(i).Name}, {AssemblyUtils.GetParameterHome(i).AsmName}"
            ))}");
        _writer.Comment("Prologue");

        if (!_currentFunctionMetaData.IsLeaf || _optimizationLevel == OptimizationLevel.None)
        {
            Push(RegisterOperand.Rbp);
            Move(RegisterOperand.Rbp, RegisterOperand.Rsp);
        }
        _rspParity = 0;


        var frameSize = _localsSize + _tempMax;
        if (frameSize != 0)
            _writer.Append($"sub rsp, {frameSize}");

        //for (var i = 0; i < Math.Min(4, function.Parameters.Count + (function.IsInstance ? 1 : 0)); i++)
        //{
        //    Move(AssemblyUtils.GetParameterLocation(i, true), AssemblyUtils.GetParameterLocation(i, false));
        //}

        _writer.Comment("Prologue End");

        _writer.RestoreLine();
    }

    public void EmitStatement(Statement statement)
    {
        if (statement is (Return or Break or VariableDeclaration or Expression))
        {
            _writer.Comment(_source.Substring(statement.Span.Start, statement.Span.Length));
        }

        Debug.WriteLine("###################################");
        Debug.WriteLine("STATEMENT: ");
        Debug.WriteLine(_regPool.FreeCount);
        Debug.WriteLine(_source.Substring(statement.Span.Start, statement.Span.Length));
        Debug.WriteLine("###################################");
        switch (statement)
        {
            case Block block:
                {
                    foreach (var s in block.Statements)
                        EmitStatement(s);
                    break;
                }
            case VariableDeclaration declaration:
                EmitVariableDeclaration(declaration);
                break;
            case IfStatement ifStatement:
                {
                    var endIfLabel = _writer.CreateLabel("endif");
                    var elseLabel = ifStatement.Else == null ? "" : _writer.CreateLabel("else");

                    _writer.Comment($"if({_source.Substring(ifStatement.Expression.Span.Start, ifStatement.Expression.Span.Length)})");

                    var tmp = EmitExpression(ifStatement.Expression);
                    _regPool.EnsureRegister(tmp);
                    Test(tmp.Reg, tmp.Reg);
                    _regPool.Release(tmp);
                    Jump(ifStatement.Else == null ? endIfLabel : elseLabel, Comparison.Zero);
                    EmitStatement(ifStatement.Body);

                    if (ifStatement.Else != null)
                    {
                        Jump(endIfLabel);
                        _writer.Label(elseLabel);
                        EmitStatement(ifStatement.Else);
                    }

                    _writer.Label(endIfLabel);
                    break;
                }
            case WhileStatement whileStatement:
                {
                    var loopLabel = _writer.CreateLabel("loop");
                    var endWhileLabel = _writer.CreateLabel("endWhile");
                    _currentBreakLabel = endWhileLabel;

                    _writer.Label(loopLabel);
                    var tmp = EmitExpression(whileStatement.Expression);
                    _regPool.EnsureRegister(tmp);
                    Test(tmp.Reg, tmp.Reg);
                    _regPool.Release(tmp);
                    Jump(endWhileLabel, Comparison.Zero);
                    EmitStatement(whileStatement.Body);
                    Jump(loopLabel);
                    _writer.Label(endWhileLabel);

                    break;
                }
            case ForStatement forStatement:
                {
                    var loopLabel = _writer.CreateLabel("loop");
                    var endForLabel = _writer.CreateLabel("endFor");
                    _currentBreakLabel = endForLabel;

                    EmitStatement(forStatement.Initial);
                    _writer.Label(loopLabel);
                    var tmp = EmitExpression(forStatement.Expression);
                    Test(tmp.Reg, tmp.Reg);
                    _regPool.Release(tmp);
                    Jump(endForLabel, Comparison.Zero);
                    EmitStatement(forStatement.Body);
                    EmitStatement(forStatement.Increment);
                    Jump(loopLabel);
                    _writer.Label(endForLabel);
                    break;
                }
            case Break:
                Jump(_currentBreakLabel);
                break;
            case Expression expression:
                EmitExpressionInto(expression, null);
                break;
            case Return returnStatement:
                EmitReturn(returnStatement);
                break;
            default:
                {
                    throw new Exception($"Unknown statement type{statement.GetType()}");
                }
        }
    }

    public void EmitVariableDeclaration(VariableDeclaration declaration)
    {
        var symbol = _model.GetSymbol<VariableSymbol>(declaration.Id);

        if (declaration.Initial != null)
        {
            if (declaration is not ArrayDeclaration)
            {
                EmitVariableAssignment(GetVariableDeclarationLocation(declaration), declaration.Initial);
            }
            else
            {
                if (declaration.Initial is ArrayInitializerListExpression aile)
                {
                    for (var i = 0; i < aile.Elements.Count; i++)
                    {
                        EmitVariableAssignment(GetVariableDeclarationLocation(declaration, i), aile.Elements[i]);
                    }
                }
            }
        }
        else
        {

            for (var i = 0; i < symbol.Count; i++)
                Move(GetVariableDeclarationLocation(declaration, i), ImmediateOperand.Zero);
        }

    }
    private void EmitReturn(Return returnStatement)
    {
        if (returnStatement.Expression != null)
        {
            EmitExpressionInto(returnStatement.Expression, RegisterOperand.Rax);
        }

        if (_isMain)
        {
            Move(RegisterOperand.Rcx, RegisterOperand.Rax);
            EmitFunctionCall("ExitProcess", 0);
        }
        else
        {
            if (_currentFunctionMetaData.IsLeaf && _optimizationLevel != OptimizationLevel.None)
            {
                var frameSize = _localsSize + _tempMax;
                if (frameSize != 0)
                    _writer.Append($"add rsp, {frameSize}");
            }
            else
            {
                Move(RegisterOperand.Rsp, RegisterOperand.Rbp);
                Pop(RegisterOperand.Rbp);
            }
            _writer.Append("ret");
        }
    }



    private TempHandle EmitExpression(Expression expression)
    {
        var exprType = GetExpressionType(expression);
        Debug.Assert(FitsInRegister(exprType.Size) || exprType.Size == 0);
        switch (expression)
        {
            case IntegerLiteralExpression intLit:
                return TempHandle.Imm(intLit.Value, 4);
            case FloatLiteralExpression floatLit:
                {
                    var size = floatLit.IsDouble ? 8 : 4;
                    var xr = _regPool.AcquireXmm();
                    Move(xr.Reg, MemoryOperand.FromLabel($"LC_{_model.LiteralConstantMap[floatLit.Id]}", size));
                    return xr;
                }
            case BooleanLiteralExpression boolLit:
                return TempHandle.Imm(boolLit.Value ? 1 : 0, 4);
            case StringLiteralExpression strLit:
                var strConstId = _model.LiteralConstantMap[strLit.Id];
                var strConst = _model.LiteralConstants[strConstId] as StringConstant;
                var strLbl = $"LC{strConstId}";
                EmitHeapAllocation(new ImmediateOperand(16, 8));
                var strPtr = _regPool.AcquireReturn(false);
                Move(MemoryOperand.FromDisplacement(strPtr.Reg.Register, 0, 8), MemoryOperand.FromLabel(strLbl, 8));
                Move(MemoryOperand.FromDisplacement(strPtr.Reg.Register, 8, 4), new ImmediateOperand(strConst.Text.Length, 4));
                return TempHandle.Gpr(RegisterOperand.Rax, 8);

            case VariableExpression varExpr:
                {
                    var sym = _model.GetSymbol<SymbolWithType>(varExpr.Id);

                    if (sym is FieldSymbol fieldSymbol)
                    {
                        var thisPtr = GetParameterHandle(0);
                        if (thisPtr.IsRegister)
                            return TempHandle.StableMem(thisPtr, fieldSymbol.Offset, exprType.Size, exprType.IsFloat);
                        var tmp = _regPool.AcquireGpr();
                        Move(tmp.Reg, thisPtr.Op);
                        return TempHandle.OwnedMem(tmp, fieldSymbol.Offset, exprType.Size, exprType.IsFloat);
                    }
                    else
                    {
                        var op = GetVariableAsOperand(varExpr);
                        return TempHandle.Any(op, exprType.Size, exprType.IsFloat);
                    }
                }
            case CallExpression callExpr:
                EmitCallExpression(callExpr);
                return exprType.IsFloat
                    ? TempHandle.Xmm(RegisterOperand.Xmm0, exprType.Size)
                    : TempHandle.Gpr(RegisterOperand.Rax, exprType.Size);
            case UnaryExpression unaryExpr:
                return EmitUnary(unaryExpr);
            case BinaryExpression binaryExpr:
                return EmitBinary(binaryExpr);
            case IndexExpression indExpr:
                {
                    var addrHandle = CalculateAddress(indExpr);
                    var res = _regPool.AcquireRegister(exprType.IsFloat);
                    Move(res.Op, addrHandle.Op);
                    FreeHandle(addrHandle);
                    return res;
                }
            case MemberAccessExpression accExpr:
                {
                    var b = EmitExpression(accExpr.Base);
                    var fieldSymbol = _model.GetSymbol<FieldSymbol>(accExpr.Id);
                    Add(b.Op, new ImmediateOperand(fieldSymbol.Offset, 8));
                    return b;
                }
            case MemberCallExpression memCallExpr:
                EmitMemberCallExpression(memCallExpr);
                return exprType.IsFloat
                    ? TempHandle.Xmm(RegisterOperand.Xmm0, exprType.Size)
                    : TempHandle.Gpr(RegisterOperand.Rax, exprType.Size);
            case MakeExpression makeExpression:
                return EmitMakeExpression(makeExpression);
            default:
                throw new NotSupportedException($"Expression not handled: {expression.GetType().Name}");
        }
    }
    private void EmitExpressionInto(Expression expression, Operand? destination)
    {
        switch (expression)
        {
            //case BinaryExpression binaryExpression:
            //    EmitBinary(binaryExpression, destination);
            //    break;

            default:
                var tmp = EmitExpression(expression);
                if (destination != null)
                    Move(destination, tmp.Op);
                FreeHandle(tmp);
                break;
        }
    }


    /// <summary>
    /// Return a handle for a MemoryOperand pointing to the L-Value of the expression
    /// </summary>
    private TempHandle CalculateAddress(Expression expression)
    {
        var exprType = GetExpressionType(expression);
        switch (expression)
        {
            case VariableExpression varExpr:
                {
                    var sym = _model.GetSymbol<SymbolWithType>(varExpr.Id);
                    if (sym is FieldSymbol fieldSymbol)
                    {
                        var thisPtr = GetParameterLocation(_model.GetSymbol<ParameterSymbol>(_currentFunction.Parameters[0].Id));
                        if (thisPtr is RegisterOperand reg)
                        {
                            var tmp = _regPool.AcquireGpr();
                            Lea(tmp.Reg, MemoryOperand.FromDisplacement(reg.Register, fieldSymbol.Offset, exprType.Size));
                            return TempHandle.OwnedMem(tmp, 0, exprType.Size, exprType.IsFloat);
                        }
                        else
                        {
                            var tmp = _regPool.AcquireGpr();
                            Move(tmp.Reg, thisPtr);
                            Lea(tmp.Reg, MemoryOperand.FromDisplacement(tmp.Reg.Register, fieldSymbol.Offset, exprType.Size));
                            return TempHandle.OwnedMem(tmp, 0, exprType.Size, exprType.IsFloat);
                        }
                    }
                    else
                    {
                        var varOp = GetVariableAsOperand(varExpr);
                        if (varOp is RegisterOperand varReg) throw new NotSupportedException();
                        return TempHandle.StableMem(varOp as MemoryOperand, exprType.Size, exprType.IsFloat);
                    }
                }
            case IndexExpression indExpr:
                {
                    if (LeftFirst(indExpr.Base, indExpr.Base))
                    {
                        var bse = EmitExpression(indExpr.Base);
                        _regPool.EnsureRegisterAndPin(bse);
                        var idx = EmitExpression(indExpr.Index);
                        _regPool.EnsureRegister(idx);
                        Lea(idx.Reg, MemoryOperand.FromIndex(bse.Reg.Register, idx.Reg.Register, exprType.Size, 0, exprType.Size));
                        _regPool.Release(bse);
                        return idx;
                    }
                    else
                    {
                        var idx = EmitExpression(indExpr.Index);
                        _regPool.EnsureRegisterAndPin(idx);
                        var bse = EmitExpression(indExpr.Base);
                        _regPool.EnsureRegister(bse);
                        Lea(idx.Reg, MemoryOperand.FromIndex(bse.Reg.Register, idx.Reg.Register, exprType.Size, 0, exprType.Size));
                        _regPool.Release(bse);
                        return idx;
                    }
                }
            case MemberAccessExpression memberAccess:
                {
                    var fieldSym = _model.GetSymbol<FieldSymbol>(memberAccess.Id);

                    var bse = EmitExpression(memberAccess.Base);
                    _regPool.EnsureRegister(bse);

                    var tmp = _regPool.AcquireGpr();
                    Lea(tmp.Reg, MemoryOperand.FromDisplacement(bse.Reg.Register, fieldSym.Offset, exprType.Size));

                    _regPool.Release(bse);
                    return TempHandle.OwnedMem(tmp, 0, exprType.Size, exprType.IsFloat);
                }
        }

        throw new NotSupportedException();
    }


    private void EmitCallExpression(CallExpression callExpression)
    {
        var funcSym = _model.GetSymbol<CallableSymbol>(callExpression.Id);
        var callName = Utils.Utils.SanitizeFqn(funcSym.FullyQualifiedName);

        SpillParameters();
        EmitFunctionCall(callName, callExpression.Arguments);
    }
    private void EmitMemberCallExpression(MemberCallExpression memCallExpr)
    {
        var methSym = _model.GetSymbol<CallableSymbol>(memCallExpr.Id);
        var callName = Utils.Utils.SanitizeFqn(methSym.FullyQualifiedName);
        var baseType = _model.ExpressionData[memCallExpr.Base.Id].Type;

        if (baseType is ScopeTypeSymbol)
        {
            EmitFunctionCall(callName, memCallExpr.Arguments);
        }
        else
        {
            Debug.Assert(baseType is ClassTypeSymbol);
            EmitFunctionCall(callName, [memCallExpr.Base, .. memCallExpr.Arguments]);
        }
    }
    private TempHandle EmitMakeExpression(MakeExpression makeExpression)
    {
        var classSymbol = _model.GetSymbol<ClassSymbol>(makeExpression.Id);
        var constructorSymbol = _model.GetSymbol<CallableSymbol>(makeExpression.Call.Id);
        var callName = Utils.Utils.SanitizeFqn(constructorSymbol.FullyQualifiedName);
        var arguments = (makeExpression.Call as CallExpression)?.Arguments ??
                        (makeExpression.Call as MemberCallExpression)!.Arguments;



        EmitHeapAllocation(new ImmediateOperand(classSymbol.Type.Size, 8));
        var tmp = _regPool.AcquireGpr();
        Move(tmp.Reg, RegisterOperand.Rax); //TODO: Ensure constructor returns this so this line can be removed
        EmitFunctionCall(callName, RegisterOperand.Rax, arguments);

        return tmp;
    }
    private TempHandle EmitBinary(BinaryExpression binaryExpression, Operand? destination = null)
    {
        var resType = GetExpressionType(binaryExpression);
        if (binaryExpression.Operator.Type == OperatorType.Assign)
        {
            return EmitAssignment(binaryExpression);

        }

        //if (_model.ExpressionData[binaryExpression.Id].Type.Name == "string")
        //{
        //    EmitStringOperation(binaryExpression);
        //    return;
        //}

        if (Operator.CompoundOperatorTypes.Contains(binaryExpression.Operator.Type))
        {
            return EmitCompoundOperation(binaryExpression);
        }
        var (expr0, expr1) = OrderExpressions(binaryExpression.Left, binaryExpression.Right);

        var left = EmitExpression(expr0);
        //_regPool.EnsureRegisterAndPin(left);
        //_regPool.EnsureNotMemory(left);
        var right = EmitExpression(expr1);
        //_regPool.EnsureRegister(right);
        //_regPool.Unpin(left);

        if (expr0 != binaryExpression.Left)
        {
            (left, right) = (right, left);
        }

        var willModify = WillModifyOperands(binaryExpression, left, right);
        if (willModify.left) _regPool.EnsureNotMemory(left);
        if (willModify.right) _regPool.EnsureNotMemory(right);

        if (binaryExpression.Operator.Type is OperatorType.Div or OperatorType.Mod)
        {
            _regPool.EnsureSpecificRegister(left, Register.Rax);
            _regPool.EnsureSpecificRegister(right, Register.Rdx);
        }

        if (!left.IsRegister && !right.IsRegister)
        {
            //_regPool.EnsureRegister(left);
        }


        var returnInRight = false;

        switch (binaryExpression.Operator.Type)
        {
            case OperatorType.Add:
                returnInRight = Add(left.Op, right.Op);
                break;

            case OperatorType.Sub:
                returnInRight = Sub(left.Op, right.Op);
                break;

            case OperatorType.Mul:
                returnInRight = Mul(left.Op, right.Op);
                break;

            case OperatorType.Div:
                Div(left.Op, right.Op);
                break;

            case OperatorType.Mod:
                Mod(left.Op, right.Op);
                returnInRight = true;
                break;

            case OperatorType.Equal:
                Cmp(left.Op, right.Op);
                Setcc(left.Op, Comparison.Equal);
                ZeroExtend((RegisterOperand)left.Op with { Size = 1 });
                break;


            case OperatorType.NotEqual:
                Cmp(left.Op, right.Op);
                Setcc(left.Op, Comparison.NotEqual);
                ZeroExtend((RegisterOperand)left.Op with { Size = 1 });
                break;

            case OperatorType.Less:
                Cmp(left.Op, right.Op);
                Setcc(left.Op, Comparison.LessThan);
                ZeroExtend((RegisterOperand)left.Op with { Size = 1 });
                break;

            case OperatorType.LessOrEqual:
                Cmp(left.Op, right.Op);
                Setcc(left.Op, Comparison.LessOrEqual);
                ZeroExtend((RegisterOperand)left.Op with { Size = 1 });
                break;

            case OperatorType.Greater:
                Cmp(left.Op, right.Op);
                Setcc(left.Op, Comparison.GreaterThan);
                ZeroExtend((RegisterOperand)left.Op with { Size = 1 });
                break;

            case OperatorType.GreaterOrEqual:
                Cmp(left.Op, right.Op);
                Setcc(left.Op, Comparison.GreaterOrEqual);
                ZeroExtend((RegisterOperand)left.Op with { Size = 1 });
                break;
            default:
                throw new NotSupportedException($"Binary {binaryExpression.Operator.Symbol}");
        }



        _regPool.Release(returnInRight ? left : right);
        return returnInRight ? right : left;
    }
    private TempHandle EmitUnary(UnaryExpression unaryExpression)
    {
        switch (unaryExpression.Operator.Type)
        {
            case OperatorType.PreIncrement:
                return EmitIncrementDecrement(unaryExpression.Operand, true, true);
            case OperatorType.PreDecrement:
                return EmitIncrementDecrement(unaryExpression.Operand, false, true);
            case OperatorType.PostIncrement:
                return EmitIncrementDecrement(unaryExpression.Operand, true, false);
            case OperatorType.PostDecrement:
                return EmitIncrementDecrement(unaryExpression.Operand, false, false);
            case OperatorType.Neg:
                {
                    var op = EmitExpression(unaryExpression.Operand);
                    _regPool.EnsureRegister(op);
                    Neg(op.Op);
                    return op;
                }
            case OperatorType.Address:
                {
                    var varExpr = (unaryExpression.Operand as VariableExpression) ?? throw new Exception("Tried to get the address of an r-value");
                    var loc = GetVariableAsOperand(varExpr);
                    var tmp = _regPool.AcquireGpr();
                    Lea(tmp.Reg, loc);
                    return tmp;
                }
            case OperatorType.Dereference: // *a
                {
                    var resType = GetExpressionType(unaryExpression);

                    var op = EmitExpression(unaryExpression.Operand);
                    _regPool.EnsureRegister(op);
                    Move(op.Reg, MemoryOperand.FromRegister(op.Reg.Register, 8));
                    return op;
                }
            case OperatorType.LogicalNot: // !
                {
                    var op = EmitExpression(unaryExpression.Operand);
                    _regPool.EnsureRegister(op);
                    Cmp(op.Reg, ImmediateOperand.Zero);
                    Setcc(op.Reg, Comparison.Zero);
                    ZeroExtend(op.Reg with { Size = 1 });
                    return op;
                }

            default: throw new NotSupportedException($"Unary not handled '{unaryExpression.Operator.Symbol}'");
        }
    }

    private void EmitStringOperation(BinaryExpression expression)
    {

        if (expression.Operator.Type == OperatorType.Add)
        {
            //if (_model.ExpressionData[expression.Left.Id].Type == Types.String)
            //{
            //    //Load string length;
            //}
        }
        //return EmitResult.Address();
    }
    private void EmitStringConcatenation(ConcatenationList concatenationList)
    {
        //if (concatenationList.List.Count == 1)
        //    return EmitExpression(concatenationList.List[0]);
        //
        //var tmpVar = AllocateTemp(16);
        //
        //
        //Move(tmpVar.WithOffset(8, 4), new ImmediateOperand(0, 4));
        ////Move(new MemoryOperand(GetLocation(tmpVarOff, 8), 4), new ImmediateOperand(0, 4));
        //
        ////Calculate result size
        //foreach (var expr in concatenationList.List)
        //{
        //    var type = _model.ExpressionData[expr.Id].Type;
        //    EmitExpression(expr);
        //
        //    if (type.Name == "string")
        //    {
        //        Move(new RegisterOperand("rax", 4), new MemoryOperand("[rax+8]", 4));
        //        Add(new MemoryOperand(GetLocation(tmpVarOff, 8), 4), new MemoryOperand("rax", 4));
        //    }
        //    else
        //    {
        //        throw new NotImplementedException();
        //    }
        //}
        //
        //EmitHeapAllocation(new MemoryOperand(GetLocation(tmpVarOff, 8), 4));
        //
        //
        //Move(new MemoryOperand(GetLocation(tmpVarOff), 8), new RegisterOperand("rax", 8)); //Place heap ptr in string struct
        //
        //
        //Push(new RegisterOperand("rax", 8));
        //foreach (var expr in concatenationList.List)
        //{
        //    var type = _model.ExpressionData[expr.Id].Type;
        //    EmitExpression(expr);
        //
        //    if (type.Name == "string")
        //    {
        //        Pop(new RegisterOperand("r10", 8));
        //
        //        Move(new RegisterOperand("r11", 8), new MemoryOperand("[rax]", 8));
        //        Move(new RegisterOperand("rcx", 4), new MemoryOperand("[rax+8]", 4));
        //
        //
        //        //rax: ptr to string (ptr*, len)*
        //        //r10: heap ptr
        //        //r11: str data ptr
        //        //rcx: bytes left
        //
        //
        //        var lblLoop = _writer.CreateLabel("str_copy");
        //        var lblEnd = _writer.CreateLabel("str_copy_end");
        //
        //        _writer.Label(lblLoop);
        //
        //        BinaryInstruction("test", new RegisterOperand("rcx", 4), new RegisterOperand("rcx", 4));
        //        _writer.Append($"jz {lblEnd}");
        //
        //        Move(new RegisterOperand("rdx", 1), new MemoryOperand("[r11]", 1));
        //        Move(new MemoryOperand("[r10]", 1), new RegisterOperand("rdx", 1));
        //
        //
        //
        //        _writer.Append($"inc {GetRegister("r11", 8)}"); //Increase form string pointer
        //        _writer.Append($"inc {GetRegister("r10", 8)}"); //Increase to string pointer
        //        _writer.Append($"dec {GetRegister("rcx", 4)}"); //Decrease bytes left
        //        _writer.Append($"jmp {lblLoop}");
        //        _writer.Label(lblEnd);
        //
        //
        //
        //        Push(new RegisterOperand("r10", 8));
        //    }
        //    else
        //    {
        //        throw new NotImplementedException();
        //    }
        //}
        //
        //
        //Pop(new RegisterOperand("rax", 8));
        //
        //Lea(RegisterOperand.Rax, new MemoryOperand(GetLocation(tmpVarOff), 8));
        //
        //return EmitResult.Address();
        throw new NotSupportedException();
    }
    private void EmitStringInterpolation(StringInterpolationExpression interpolation)
    {
        throw new NotImplementedException();
    }

    private TempHandle EmitCompoundOperation(BinaryExpression expression)
    {
        if (expression.Left is not VariableExpression varExpr)
            throw new NotSupportedException("Can only assign to lvalues");

        var varOp = GetVariableAsOperand(varExpr);
        var varType = GetExpressionType(expression.Left);

        var isLit = expression.Right.IsNumericLiteral();
        var litVal = isLit ? expression.Right.GetNumericalLiteralValue() : -1;

        var isPtr = false;
        var ptrTypeSize = 0;



        if (varType is PointerTypeSymbol ptr)
        {
            isPtr = true;
            ptrTypeSize = ptr.Type.Size;
            litVal *= ptrTypeSize;
        }


        if (isLit && expression.Operator.Type is (OperatorType.AddAssign or OperatorType.SubAssign or OperatorType.MulAssign))
        {
            switch (expression.Operator.Type)
            {
                case OperatorType.AddAssign: Add(varOp, new ImmediateOperand(litVal, varOp.Size)); break;
                case OperatorType.SubAssign: Sub(varOp, new ImmediateOperand(litVal, varOp.Size)); break;
                case OperatorType.MulAssign: Mul(varOp, new ImmediateOperand(litVal, varOp.Size)); break;
            }

            var tmp = _regPool.AcquireGpr();
            Move(tmp.Op, varOp);
            return tmp;
        }

        var right = EmitExpression(expression.Right);
        _regPool.EnsureRegister(right);
        if (isPtr) Mul(right.Op, new ImmediateOperand(ptrTypeSize, 4));

        switch (expression.Operator.Type)
        {
            case OperatorType.AddAssign: Add(varOp, right.Op with { Size = varOp.Size }); break;
            case OperatorType.SubAssign: Sub(varOp, right.Op with { Size = varOp.Size }); break;
            case OperatorType.MulAssign: Mul(varOp, right.Op with { Size = varOp.Size }); break;
            case OperatorType.DivAssign: Div(varOp, right.Op with { Size = varOp.Size }); break;
            case OperatorType.ModAssign: Mod(varOp, right.Op with { Size = varOp.Size }); break;
        }



        Move(right.Op, varOp);
        return right;
    }
    private TempHandle EmitAssignment(BinaryExpression expression)
    {
        var leftType = GetExpressionType(expression.Left);
        var rightType = GetExpressionType(expression.Right);


        if (LeftFirst(expression.Left, expression.Right))
        {
            var leftHandle = CalculateAddress(expression.Left);
            _regPool.EnsureRegisterAndPin(leftHandle);
            var right = EmitExpression(expression.Right);
            _regPool.EnsureRegister(right);

            Move(leftHandle.Op, right.Reg);
            FreeHandle(leftHandle);
            return right;
        }
        else
        {
            var right = EmitExpression(expression.Right);
            _regPool.EnsureRegisterAndPin(right);
            var leftHandle = CalculateAddress(expression.Left);
            Move(leftHandle.Op, right.Reg);

            FreeHandle(leftHandle);
            UnpinHandle(right);
            return right;
        }
    }

    private void EmitMemberAccess(MemberAccessExpression memberAccess, Operand destination)
    {
        var baseType = GetExpressionType(memberAccess.Base);

        {
            if (baseType is ClassTypeSymbol classTypeSymbol)
            {
                var fieldSymbol = _model.GetSymbol<FieldSymbol>(memberAccess.Id);
                if (memberAccess.Base is VariableExpression varExpr)
                {
                    var ptrOp = GetVariableAsOperand(varExpr);

                    Move(RegisterOperand.Rax, ptrOp);

                    var regSize = Math.Max(4, fieldSymbol.Type.Size);
                    Move(destination with { Size = regSize },
                        MemoryOperand.FromDisplacement(Register.Rax, classTypeSymbol.FieldOffset[fieldSymbol.Id], regSize));

                    return;
                    //return IsFloatOperand(destination) ? EmitResult.FloatValue(regSize) : EmitResult.Value(regSize);
                }
            }
        }
        throw new NotSupportedException($"Expression not handled: '{memberAccess.Member}' on '{baseType}'"); ;
    }



    private void EmitHeapAllocation(Operand lengthOperand)
    {
        EmitFunctionCall("GetProcessHeap", 0);

        //Move(RegisterOperand.R11, lengthOperand);

        EmitFunctionCall("HeapAlloc", 0, () =>
        {
            Move(RegisterOperand.Rcx, RegisterOperand.Rax);
            Xor(RegisterOperand.Rdx, RegisterOperand.Rdx);
            Move(RegisterOperand.R8, lengthOperand);
        });
    }


    private void EmitFunctionCall(string name, Operand firstParameter, IReadOnlyList<Expression> arguments)
    {
        EmitFunctionCall(name,
            arguments.Count,
            () =>
            {
                Move(AssemblyUtils.GetParameterRegisterOperand(0), firstParameter);
                for (var i = 0; i < arguments.Count; i++)
                {
                    var argType = _model.ExpressionData[arguments[i].Id].Type;
                    var size = argType.IsReferenceType ? 8 : argType.Size;
                    EmitExpressionInto(arguments[i], AssemblyUtils.GetParameterLocation(i + 1, false));
                }
            }
        );
    }
    private void EmitFunctionCall(string name, IReadOnlyList<Expression> arguments)
    {
        //Function1(1, x, Func2(1, 5), 5);
        EmitFunctionCall(name,
            arguments.Count,
            () =>
            {
                _regPool.SpillAll();

                var numCalls = arguments.Count(ContainsCall);
                var sortedArguments = OrderExpressions(arguments);

                var callCount = 0;
                foreach (var arg in sortedArguments)
                {
                    if (ContainsCall(arg.expression)) callCount++;

                    if (callCount < numCalls)
                    {
                        // AllocateTemp(bytes);
                        EmitExpressionInto(arg.expression, AssemblyUtils.GetParameterLocation(arg.index, false));
                    }
                    else if (callCount == numCalls)
                    {
                        EmitExpressionInto(arg.expression, AssemblyUtils.GetParameterLocation(arg.index, false));
                    }
                    else
                    {
                        EmitExpressionInto(arg.expression, AssemblyUtils.GetParameterLocation(arg.index, false));
                    }
                }
            }
        );
    }
    private void EmitFunctionCall(string name, int argCount, Action? preCall = null)
    {

        var reserve = Math.Max(argCount * 8, 32);

        if (_rspParity % 16 != 0) reserve += (16 - _rspParity % 16);

        SubRsp(reserve);

        preCall?.Invoke();
        _writer.Append($"call {name}");
        AddRsp(reserve);
    }

    private void EmitVariableAssignment(MemoryOperand operand, Expression expression)
    {
        if (expression.IsNumericLiteral())
        {
            Move(operand, new ImmediateOperand(expression.GetNumericalLiteralValue(), operand.Size));
        }
        else
        {
            EmitExpressionInto(expression, operand);
        }
    }

    //Unaries
    private TempHandle EmitIncrementDecrement(Expression expression, bool increment, bool prefix)
    {
        var type = GetExpressionType(expression);
        var addrHandle = CalculateAddress(expression);
        var tmp = _regPool.AcquireGpr(type.Size);

        if (prefix)
        {
            if (increment) Inc(addrHandle.Op); else Dec(addrHandle.Op);
            Move(tmp.Reg, addrHandle.Op);
        }
        else
        {
            Move(tmp.Reg, addrHandle.Op);
            if (increment) Inc(addrHandle.Op); else Dec(addrHandle.Op);
        }

        FreeHandle(addrHandle);

        return tmp;
    }

    void PinHandle(TempHandle handle)
    {
        foreach (var register in handle.OwnedHandles)
        {
            _regPool.Pin(register);
        }

    }
    void UnpinHandle(TempHandle handle)
    {
        foreach (var register in handle.OwnedHandles)
        {
            _regPool.Unpin(register);
        }

    }
    void FreeHandle(TempHandle handle)
    {
        foreach (var register in handle.OwnedHandles)
        {
            _regPool.Release(register);
        }
        _regPool.Release(handle);
    }

    private void SpillParameters()
    {
        for (var i = 0; i < Math.Min(4, _currentFunction.Parameters.Count); i++)
        {
            SpillParameter(i);
        }
    }
    private void SpillParameter(int index)
    {
        Debug.Assert(index is >= 0 and < 4);
        if (!_parameterSpilled[index])
        {
            Move(AssemblyUtils.GetParameterHome(index), AssemblyUtils.GetParameterRegisterOperand(index));
            _parameterSpilled[index] = true;
            _regPool.Release(_currentParameters[index]);
        }
    }
    private void ForgetParameter(int index) => throw new NotImplementedException();




    //Helpers (Do not write to assembly)
    private TypeSymbol GetExpressionType(Expression expr) => _model.ExpressionData[expr.Id].Type;
    private bool ContainsCall(Expression expr) => _model.ExpressionData[expr.Id].ContainsCall;
    private TypeSymbol GetElementType(TypeSymbol baseType)
    {
        return baseType is PointerTypeSymbol p ? p.Type
            : baseType is ArrayTypeSymbol a ? a.Type
            : throw new NotSupportedException("Only array and pointer types can be indexed");
    }

    private (bool left, bool right) WillModifyOperands(BinaryExpression expression, TempHandle leftHandle, TempHandle rightHandle)
    {

        // 5 - x    

        if (expression.Left.IsNumericLiteral())
        {
            return (false, true);
        }

        return (true, false);
    }

    int SethiUllman(Expression expr)
    {
        int Junction(Expression left, Expression right)
        {
            var l = SethiUllman(left);
            var r = SethiUllman(right);
            return (l == r) ? l + 1 : Math.Max(l, r);
        }

        switch (expr)
        {
            case BinaryExpression bin: return Junction(bin.Left, bin.Right);
            case UnaryExpression un: return SethiUllman(un.Operand);           //IF I CAN ENSURE IN MEMORY INC/DEC
            case IndexExpression ind: return Junction(ind.Base, ind.Index);
            case MemberAccessExpression mem: return SethiUllman(mem.Base);
            default: return 1;
        }
    }

    private bool LeftFirst(Expression left, Expression right)
    {
        if (ContainsCall(left) && !ContainsCall(right)) return true;
        if (ContainsCall(right) && !ContainsCall(left)) return false;
        return SethiUllman(left) >= SethiUllman(right);
    }
    private (Expression expr0, Expression expr1) OrderExpressions(Expression left, Expression right) => LeftFirst(left, right) ? (left, right) : (right, left);

    private IEnumerable<(Expression expression, int index)> OrderExpressions(IEnumerable<Expression> expressions)
    {
        return expressions.Select((exp, ind) => (exp, ind)).OrderByDescending(x => ContainsCall(x.exp)).ThenByDescending(y => SethiUllman(y.exp));
    }


    private MemoryOperand AllocateTemp(int bytes)
    {
        _tempCursor += bytes;
        var off = _localsSize + _tempCursor;
        _tempMax = Math.Max(_tempMax, _tempCursor);
        return MemoryOperand.FromDisplacement(Register.Rbp, -off, bytes);
    }


    private Register FramePointer => _currentFunctionMetaData.IsLeaf ? Register.Rsp : Register.Rbp;
    private Operand GetVariableAsOperand(VariableExpression variableExpression)
    {
        var sym = _model.GetSymbol(variableExpression.Id);
        if (sym is VariableSymbol varSym)
            return MemoryOperand.FromDisplacement(FramePointer, -varSym.Offset, varSym.Type.Size);
        if (sym is ParameterSymbol parSym)
            return GetParameterLocation(parSym);


        throw new Exception("Cannot find variable");
    }
    private TempHandle GetParameterHandle(int index) => _currentParameters[index];
    private Operand GetParameterLocation(ParameterSymbol parSym)
    {

        var isSpilled = parSym.Index < 4 && _parameterSpilled[parSym.Index];
        return AssemblyUtils.GetParameterLocation(parSym.Index, isSpilled);
        //return $"[rbp + {16 + parSym.Index * 8 + byteOffset}]";
    }

    private MemoryOperand GetVariableLocation(VariableSymbol varSym, int offset = 0, int byteOffset = 0) =>
        MemoryOperand.FromDisplacement(FramePointer, -(varSym.Offset - offset * varSym.Type.Size - byteOffset), varSym.Type.Size);

    private MemoryOperand GetVariableDeclarationLocation(VariableDeclaration declaration, int offset = 0, int byteOffset = 0)
    {
        return GetVariableLocation(_model.GetSymbol<VariableSymbol>(declaration.Id), offset, byteOffset);
    }
    private string GetSizeModifier(int size) => size switch { 1 => "byte", 2 => "word", 4 => "dword", 8 => "qword", _ => throw new NotSupportedException($"Incorrect size '{size}'") };
    private bool FitsInRegister(int size) => size is 1 or 2 or 4 or 8;
    private string GetStringConstLabel(int stringConstId) => $"str_{stringConstId}_";
    private bool IsFloatOperation(Operand dest, Operand src)
    {

        return dest is RegisterOperand { IsXmm: true } ||
               src is RegisterOperand { IsXmm: true };
    }

    private bool IsFloatOperand(Operand op) => op is RegisterOperand { IsXmm: true };




    //Assembly instructions (USE ONLY THESE)
    #region Assembly
    private void Move(Operand dest, Operand src, bool signed = false)
    {
        // if (dest == src)
        //     return;

        if (IsFloatOperation(dest, src))
        {
            MoveFloat(dest, src);
            return;
        }
        if (dest is MemoryOperand mDest && src is MemoryOperand sDest)
        {
            //throw new NotSupportedException("Both operands cannot be memory");
            var tmp = _regPool.AcquireGpr();
            MoveMemory(mDest, sDest, tmp.Reg);
            _regPool.Release(tmp);
            return;
        }
        if (dest is ImmediateOperand)
            throw new NotSupportedException("Immediate cannot be used as destination");

        if (dest is MemoryOperand && src is ImmediateOperand)
        {
            var destSizeModifier = GetSizeModifier(dest.Size);
            _writer.Append($"mov {destSizeModifier} {dest.AsmName}, {src.AsmName}");
        }
        else if (src.Size < dest.Size)
        {
            if (dest is MemoryOperand)
            {
                throw new NotImplementedException();
                var tmp = new RegisterOperand(Register.R15, dest.Size);
                Move(tmp, src);
                Move(dest, tmp);
            }
            else if (signed)
            {
                var srcSizeModifier = GetSizeModifier(src.Size);
                _writer.Append($"movsx {dest.AsmName}, {srcSizeModifier} {src.AsmName}");
            }
            else if (src.Size == 4)
            {
                _writer.Append($"mov {(dest with { Size = 4 }).AsmName}, {src.AsmName}");
            }
            else
            {
                var srcSizeModifier = GetSizeModifier(src.Size);
                _writer.Append($"movzx {dest.AsmName}, {srcSizeModifier} {src.AsmName}");
            }

        }
        else if (dest.Size < src.Size)
        {
            if (dest is MemoryOperand)
            {
                _writer.Append($"mov {dest.AsmName}, {((src as RegisterOperand) with { Size = dest.Size }).AsmName}");
            }
            else
            {
                _writer.Append($"mov {dest.AsmName}, {src.AsmName}");
            }

        }
        else
        {
            _writer.Append($"mov {dest.AsmName}, {src.AsmName}");
        }

    }
    private void MoveMemory(MemoryOperand dest, MemoryOperand src, RegisterOperand temporaryRegister)
    {
        if (dest.Size != src.Size)
        {
            throw new NotSupportedException($"The sizes of the operands does not match");
        }


        var bytesLeft = dest.Size;
        var offset = 0;

        while (bytesLeft > 0)
        {
            var moveSize = Math.Min(bytesLeft, temporaryRegister.Size);
            if (moveSize is not (1 or 2 or 4 or 8))
                throw new NotSupportedException();

            var from = src.WithOffset(offset, moveSize);
            var to = dest.WithOffset(offset, moveSize);
            var tmp = temporaryRegister with { Size = moveSize };

            Move(tmp, from);
            Move(to, tmp);

            offset += moveSize;
            bytesLeft -= moveSize;
        }

    }
    private void MoveFloat(Operand dest, Operand src)
    {
        Debug.Assert(IsFloatOperation(dest, src));
        Debug.Assert(src is not ImmediateOperand);
        Debug.Assert(dest is not ImmediateOperand);
        Debug.Assert(src.Size == dest.Size);

        if (dest.Size == 4)
            _writer.Append($"movss {dest.AsmName}, {src.AsmName}");
        else if (dest.Size == 8)
            _writer.Append($"movsd {dest.AsmName}, {src.AsmName}");
    }

    private void BinaryInstruction(string op, Operand dest, Operand src)
    {
        if (dest is ImmediateOperand)
            throw new NotSupportedException($"Destination cannot be an immediate '{dest}'");

        if (dest is MemoryOperand && src is MemoryOperand)
            throw new NotSupportedException("Both operands cannot be memory");


        if ((src.Size is not (4 or 8) || dest.Size is not (4 or 8)) && src.Size != dest.Size)
            throw new NotSupportedException("Operands have different sizes");

        if (src is ImmediateOperand && dest is MemoryOperand)
        {
            var sizeModifier = GetSizeModifier(dest.Size);
            _writer.Append($"{op} {sizeModifier} {dest.AsmName}, {src.AsmName}");
        }
        else
        {
            _writer.Append($"{op} {dest.AsmName}, {src.AsmName}");
        }
    }
    private void IntegerOrFloatBinaryInstruction(string normalOp, string floatOp, string doubleOp, Operand dest, Operand src)
    {

        if (IsFloatOperation(dest, src))
        {
            if (!IsFloatOperand(dest) || src is ImmediateOperand)
                throw new NotSupportedException();

            if (dest.Size == 4)
                BinaryInstruction(floatOp, dest, src);
            else if (dest.Size == 8)
                BinaryInstruction(doubleOp, dest, src);
        }
        else
        {
            BinaryInstruction(normalOp, dest, src);
        }
    }





    private void Exchange(Operand dest, Operand src) => BinaryInstruction("xchg", dest, src);
    private void Lea(Operand dest, Operand src) => BinaryInstruction("lea", dest, src with { Size = 8 });

    private void Cmp(Operand dest, Operand src) => BinaryInstruction("cmp", dest, src);
    private void Test(Operand dest, Operand src) => BinaryInstruction("test", dest, src);

    private bool Add(Operand dest, Operand src)
    {
        if (dest is ImmediateOperand imm)
        {
            IntegerOrFloatBinaryInstruction("add", "addss", "addsd", src, dest);
            return true;
        }
        else
        {
            IntegerOrFloatBinaryInstruction("add", "addss", "addsd", dest, src);
            return false;
        }
    }

    private bool Sub(Operand dest, Operand src)
    {
        if (!IsFloatOperation(dest, src) && dest is ImmediateOperand imm)
        {
            Neg(src);
            Add(src, imm);
            return true;
        }
        else
        {
            IntegerOrFloatBinaryInstruction("sub", "subss", "subsd", dest, src);
            return false;
        }
    }

    private bool Mul(Operand dest, Operand src)
    {

        if (dest is ImmediateOperand imm)
        {
            IntegerOrFloatBinaryInstruction("imul", "mulss", "mulsd", src, dest);
            return true;
        }
        else
        {
            IntegerOrFloatBinaryInstruction("imul", "mulss", "mulsd", dest, src);
            return false;
        }
    }
    private void Div(Operand dest, Operand src)
    {
        Debug.Assert(dest.Size == src.Size);
        if (IsFloatOperation(dest, src))
        {
            if (!IsFloatOperand(dest) || src is ImmediateOperand)
                throw new NotSupportedException();

            if (dest.Size == 4)
                BinaryInstruction("divss", dest, src);
            else if (dest.Size == 8)
                BinaryInstruction("divsd", dest, src);
        }
        else
        {
            if (dest is RegisterOperand { Register.Name: "rax" })
            {
                _writer.Append("cqo");
                _writer.Append($"idiv {src.AsmName}");
            }
            else
            {
                Move(RegisterOperand.Rax, dest);
                _writer.Append("cqo");
                _writer.Append($"idiv {src.AsmName}");
                Move(dest, RegisterOperand.Rax);
            }
        }
    }

    private void Mod(Operand dest, Operand src)
    {
        Debug.Assert(dest.Size == src.Size);
        if (IsFloatOperation(dest, src))
        {
            if (!IsFloatOperand(dest) || src is ImmediateOperand)
                throw new NotSupportedException();

            if (dest.Size == 4)
                BinaryInstruction("divss", dest, src);
            else if (dest.Size == 8)
                BinaryInstruction("divsd", dest, src);
        }
        else
        {
            if (dest is RegisterOperand { Register.Name: "rax" })
            {
                _writer.Append("cqo");
                _writer.Append($"idiv {src.AsmName}");
            }
            else
            {
                Move(RegisterOperand.Rax, dest);
                _writer.Append("cqo");
                _writer.Append($"idiv {src.AsmName}");
                Move(dest, RegisterOperand.Rax);
            }
        }
    }


    private void Xor(Operand dest, Operand src) => BinaryInstruction("xor", dest, src);

    private void Neg(Operand op) => _writer.Append($"neg {(op is MemoryOperand ? GetSizeModifier(op.Size) : "")}{op.AsmName}");
    private void Inc(Operand op) => _writer.Append($"inc {(op is MemoryOperand ? GetSizeModifier(op.Size) : "")}{op.AsmName}");
    private void Dec(Operand op) => _writer.Append($"dec {(op is MemoryOperand ? GetSizeModifier(op.Size) : "")}{op.AsmName}");
    private void Setcc(Operand op, Comparison comp)
    {
        var instruction = comp switch
        {
            Comparison.Equal => "sete",
            Comparison.NotEqual => "setne",
            Comparison.GreaterThan => "setg",
            Comparison.LessThan => "setl",
            Comparison.GreaterOrEqual => "setge",
            Comparison.LessOrEqual => "setle",
            Comparison.Zero => "setz",
            _ => throw new ArgumentOutOfRangeException(nameof(comp), comp, null)
        };
        _writer.Append($"{instruction} {(op with { Size = 1 }).AsmName}");
    }


    private void Jump(string label, Comparison? comparison = null)
    {
        var instruction = comparison switch
        {
            null => "jmp",
            Comparison.Equal => "je",
            Comparison.NotEqual => "jne",
            Comparison.GreaterThan => "jg",
            Comparison.LessThan => "jl",
            Comparison.GreaterOrEqual => "jge",
            Comparison.LessOrEqual => "jle",
            Comparison.Zero => "jz",
            _ => throw new ArgumentOutOfRangeException(nameof(comparison), comparison, null)
        };

        _writer.Append($"{instruction} {label}");
    }

    private void ZeroExtend(RegisterOperand op) => _writer.Append($"movzx {(op with { Size = 8 }).AsmName}, {op.AsmName}");
    private void ExtendInt(Operand dest, Operand src, bool signed)
    {
        Debug.Assert(src.Size is 1 or 2);
        Debug.Assert(dest.Size is 2 or 4 or 8);
        Debug.Assert(dest is RegisterOperand);
        Debug.Assert(src is not ImmediateOperand);
        _writer.Append($"{(signed ? "movsx" : "movzx")} {dest}, {src}");
    }
    private void IntToFloat(Operand dest, Operand src)
    {
        Debug.Assert(dest is not ImmediateOperand);
        Debug.Assert(src is not ImmediateOperand);
        Debug.Assert(IsFloatOperand(dest));

        if (dest.Size == 4)
            _writer.Append($"cvtsi2ss {dest.AsmName}, {src.AsmName}");
        else if (dest.Size == 8)
            _writer.Append($"cvtsi2sd {dest.AsmName}, {src.AsmName}");
    }
    private void FloatToInt(Operand dest, Operand src)
    {
        Debug.Assert(dest is RegisterOperand { IsGpr: true });
        Debug.Assert(src is RegisterOperand { IsXmm: true });

        if (src.Size == 4)
            _writer.Append($"cvtss2si {dest.AsmName}, {src.AsmName}");
        else if (src.Size == 8)
            _writer.Append($"cvtsd2si {dest.AsmName}, {src.AsmName}");
    }
    private void Push(Operand operand)
    {
        if (IsFloatOperand(operand))
        {
            SubRsp(16);
            _writer.Append($"movdqu [rsp], {operand.AsmName}");
            return;
        }

        //Debug.Assert(operand.Size == 8);

        _writer.Append($"push {(operand with { Size = 8 }).AsmName}");
        _rspParity = (_rspParity - 8) & 0xF;
    }
    private void Pop(Operand operand)
    {
        if (IsFloatOperand(operand))
        {
            _writer.Append($"movdqu  {operand.AsmName}, [rsp]");
            AddRsp(16);
            return;
        }

        //Debug.Assert(operand.Size == 8);

        _writer.Append($"pop {(operand with { Size = 8 }).AsmName}");
        _rspParity = (_rspParity - 8) & 0xF;
    }
    private void SubRsp(int bytes)
    {
        _writer.Append($"sub rsp, {bytes}");
        _rspParity = (_rspParity - bytes) & 0xF;
    }
    private void AddRsp(int bytes)
    {
        _writer.Append($"add rsp, {bytes}");
        _rspParity = (_rspParity + bytes) & 0xF;
    }

    #endregion
}
